---

- name: Install OpenSSH server
  package:
    name: "openssh-server"
    state: "present"

- name: Give insecure permissions to an existing file
  copy:
    src: issue.txt
    dest: /etc/issue
    owner: root
    group: root
    mode: "0644"
  notify:
   - Start Service
   

- name: Generate SSHD config
  template:
    src: "sshd_config.j2"
    dest: "/etc/ssh/sshd_config"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
   - Start Service

- firewalld:
    permanent: yes
    immediate: yes
    state: enabled
    port: "{{ sshd_port }}/tcp"


